### ISSUE TITLE
UML Diagram - Before Beginning

### ISSUE THREAD

**Issue by TravisWhitehead** [OSU-CS361-W17/group7_project3#6]
> The first diagram should represent the class structure of your Battleship game from Project Stage 2.
> These diagrams can either be composed using UML modeling software, or drawn on paper (drawings should be labelled and legible). Scan and add this diagram to your group's Wiki pages (names should be added to indicate the author of each diagram).

**Comment by CMCarlsen** [comment]
Here it is!

![prechanges](https://cloud.githubusercontent.com/assets/3077339/23448010/6c907710-fe03-11e6-924a-56b3ffee79a5.png)

**Comment by CMCarlsen** [comment]
Done and done!
