### ISSUE TITLE
New ship classes and stealth attribute

### ISSUE THREAD

**Issue by ghost** [OSU-CS361-W17/group7_project3#8]
The new project requires a different class of ships, designated "Civilian" that sinks after a single hit. The project is also asking for certain ships to gain a "Stealth" attribute that makes them invisible to scans.

**Comment by TravisWhitehead** [comment]
Looks like this was resolved in PR #11. Should we close it?

**Comment by ghost** [comment]
Yes, I was actually just about to.

**Comment by ghost** [comment]
Ship is now treated as a civilian ship. It has a subclass, MilitaryShip, that has additional variables, as well as some overridden methods for dealing with hits and scanning with respect to the stealth variable.
