### ISSUE TITLE
Fix JSON (de)serialization to remember Ship subclass types in arrays

### ISSUE THREAD

**Issue by TravisWhitehead** [OSU-CS361-W17/group7_project3#9]
We have arrays of Ships in our BattleshipModel. However, when JSON is deserialized to Java, any objects belonging to this array are constructed as Ships (instead of their subclasses), so polymorphism doesn't work.

**Comment by CMCarlsen** [comment]
Thanks for fixing this with #10. Should make the rest of this sprint much smoother. Close?

**Comment by TravisWhitehead** [comment]
Yep, #10 is merged, so this is done.
